/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailRouteImport } from './routes/email'
import { Route as MeetingNotesRouteImport } from './routes/meeting-notes'
import { Route as TasksRouteImport } from './routes/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingNotesRoute = MeetingNotesRouteImport.update({
  id: '/meeting-notes',
  path: '/meeting-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/meeting-notes': typeof MeetingNotesRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/meeting-notes': typeof MeetingNotesRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email': typeof EmailRoute
  '/meeting-notes': typeof MeetingNotesRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/email' | '/meeting-notes' | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/email' | '/meeting-notes' | '/tasks'
  id: '__root__' | '/' | '/email' | '/meeting-notes' | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailRoute: typeof EmailRoute
  MeetingNotesRoute: typeof MeetingNotesRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-notes': {
      id: '/meeting-notes'
      path: '/meeting-notes'
      fullPath: '/meeting-notes'
      preLoaderRoute: typeof MeetingNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailRoute: EmailRoute,
  MeetingNotesRoute: MeetingNotesRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
